// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BurnFuelCommand is an autogenerated mock type for the BurnFuelCommand type
type BurnFuelCommand struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *BurnFuelCommand) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLeftover provides a mock function with given fields: leftover
func (_m *BurnFuelCommand) SetLeftover(leftover int) {
	_m.Called(leftover)
}

type mockConstructorTestingTNewBurnFuelCommand interface {
	mock.TestingT
	Cleanup(func())
}

// NewBurnFuelCommand creates a new instance of BurnFuelCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBurnFuelCommand(t mockConstructorTestingTNewBurnFuelCommand) *BurnFuelCommand {
	mock := &BurnFuelCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
