// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CheckFuelCommand is an autogenerated mock type for the CheckFuelCommand type
type CheckFuelCommand struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *CheckFuelCommand) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLeftover provides a mock function with given fields: leftover
func (_m *CheckFuelCommand) SetLeftover(leftover int) {
	_m.Called(leftover)
}

type mockConstructorTestingTNewCheckFuelCommand interface {
	mock.TestingT
	Cleanup(func())
}

// NewCheckFuelCommand creates a new instance of CheckFuelCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCheckFuelCommand(t mockConstructorTestingTNewCheckFuelCommand) *CheckFuelCommand {
	mock := &CheckFuelCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
