// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	commands "github.com/bindasov/spaceBattle/commands"

	mock "github.com/stretchr/testify/mock"
)

// DoubleRepeatStrategy is an autogenerated mock type for the DoubleRepeatStrategy type
type DoubleRepeatStrategy struct {
	mock.Mock
}

// CacheCommand provides a mock function with given fields: command
func (_m *DoubleRepeatStrategy) CacheCommand(command commands.StraightMoveCommand) {
	_m.Called(command)
}

// Execute provides a mock function with given fields:
func (_m *DoubleRepeatStrategy) Execute() {
	_m.Called()
}

type mockConstructorTestingTNewDoubleRepeatStrategy interface {
	mock.TestingT
	Cleanup(func())
}

// NewDoubleRepeatStrategy creates a new instance of DoubleRepeatStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDoubleRepeatStrategy(t mockConstructorTestingTNewDoubleRepeatStrategy) *DoubleRepeatStrategy {
	mock := &DoubleRepeatStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
