// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	commands "github.com/bindasov/spaceBattle/commands"

	mock "github.com/stretchr/testify/mock"
)

// DoubleRepeatCommand is an autogenerated mock type for the DoubleRepeatCommand type
type DoubleRepeatCommand struct {
	mock.Mock
}

// CacheCommand provides a mock function with given fields: command
func (_m *DoubleRepeatCommand) CacheCommand(command commands.StraightMoveCommand) {
	_m.Called(command)
}

// Execute provides a mock function with given fields:
func (_m *DoubleRepeatCommand) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDoubleRepeatCommand interface {
	mock.TestingT
	Cleanup(func())
}

// NewDoubleRepeatCommand creates a new instance of DoubleRepeatCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDoubleRepeatCommand(t mockConstructorTestingTNewDoubleRepeatCommand) *DoubleRepeatCommand {
	mock := &DoubleRepeatCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
