// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LogCommand is an autogenerated mock type for the LogCommand type
type LogCommand struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *LogCommand) Execute() {
	_m.Called()
}

// SetError provides a mock function with given fields: err
func (_m *LogCommand) SetError(err error) {
	_m.Called(err)
}
