// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	commands "github.com/bindasov/spaceBattle/commands"

	mock "github.com/stretchr/testify/mock"
)

// RepeatCommand is an autogenerated mock type for the RepeatCommand type
type RepeatCommand struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *RepeatCommand) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: command
func (_m *RepeatCommand) CacheCommand(command commands.StraightMoveCommand) {
	_m.Called(command)
}
